Feature/refactoring
unna97/audio-annonation pull request #21
Opened 2023-07-12 20:15 UTC by arvaibhav

- refactored sync_audio_files from update database
- separate out dao ( Data Access Object design pattern)  from views 
- separate out utils from views 
- removed direct db models dependency from views

2023-07-13 10:54 UTC, unna97 requested changes
Can we change the functions to apis? Also, maybe we also need to rename functions, currently it's not very clear

2023-07-13 10:54 UTC, unna97 commented on waveform_audio/dao.py
Shouldn't we convert the SET &  GETs to apis?

2023-07-13 12:08 UTC, arvaibhav commented on waveform_audio/dao.py
Only if apis required on client side , unnecessary not required to build with test cases. However dao function still be used in same way as api https controller should not directly access db as per standard design patterns.

2023-07-17 05:12 UTC, unna97 commented on waveform_audio/dao.py
I will requires apis on client side eventuatlly.

2024-01-29 10:03 UTC, closed without merging